export const clubData = [
    { name: "4N01 Dance Team", description: "A dance team that performs various styles and participates in competitions.", link: "https://studentorg.ucsd.edu/Home/Details/17001" },
    { name: "528 @UC San Diego", description: "A community service organization focused on local outreach programs.", link: "https://studentorg.ucsd.edu/Home/Details/17002" },
    { name: "A Friend in Me at UC San Diego", description: "Provides companionship and support to individuals in need within the community.", link: "https://studentorg.ucsd.edu/Home/Details/17003" },
    { name: "A Lutheran Ministry Social (ALMS)", description: "A faith-based group offering social and spiritual activities.", link: "https://studentorg.ucsd.edu/Home/Details/17004" },
    { name: "Academic Enrichment for Relocated Students (AERS)", description: "Supports students who have relocated, providing academic resources and community.", link: "https://studentorg.ucsd.edu/Home/Details/17005" },
    { name: "Academy of Managed Care Pharmacy (AMCP at UC San Diego)", description: "Focuses on the practice of managed care pharmacy, offering educational events.", link: "https://studentorg.ucsd.edu/Home/Details/17006" },
    { name: "Acamazing", description: "An a cappella group performing a variety of musical genres.", link: "https://studentorg.ucsd.edu/Home/Details/17007" },
    { name: "Active Minds", description: "Promotes mental health awareness and education among students.", link: "https://studentorg.ucsd.edu/Home/Details/17008" },
    { name: "Acts 2 Fellowship", description: "A Christian fellowship group offering Bible studies and community service.", link: "https://studentorg.ucsd.edu/Home/Details/17009" },
    { name: "Advanced Professional Degree Consulting Club at UC San Diego", description: "Provides consulting experience and networking for advanced degree students.", link: "https://studentorg.ucsd.edu/Home/Details/17010" },
    { name: "Aequora Ballet Company", description: "A ballet company that performs classical and contemporary pieces.", link: "https://studentorg.ucsd.edu/Home/Details/17011" },
    { name: "Afghan Student Association (ASA)", description: "Promotes Afghan culture and heritage through various events.", link: "https://studentorg.ucsd.edu/Home/Details/17012" },
    { name: "Ahlul-Bayt Student Association", description: "Aims to educate about the teachings of the Ahlul-Bayt.", link: "https://studentorg.ucsd.edu/Home/Details/17013" },
    { name: "AI Sphere", description: "Focuses on artificial intelligence research and projects.", link: "https://studentorg.ucsd.edu/Home/Details/17014" },
    { name: "AIDS Awareness Alliance at UC San Diego", description: "Raises awareness about HIV/AIDS through education and events.", link: "https://studentorg.ucsd.edu/Home/Details/17015" },
    { name: "Airsoft at UC San Diego", description: "A club for airsoft enthusiasts to organize games and events.", link: "https://studentorg.ucsd.edu/Home/Details/17016" },
    { name: "All Peoples Church at UC San Diego", description: "A Christian community offering worship services and fellowship.", link: "https://studentorg.ucsd.edu/Home/Details/17017" },
    { name: "Alpha", description: "Explores the basics of the Christian faith through discussions.", link: "https://studentorg.ucsd.edu/Home/Details/17018" },
    { name: "Alpha Chi Omega", description: "A women’s fraternity promoting friendship, leadership, and service.", link: "https://studentorg.ucsd.edu/Home/Details/17019" },
    { name: "Alpha Epsilon Delta Pre-Health Professional Honor Society", description: "A society for students pursuing careers in healthcare.", link: "https://studentorg.ucsd.edu/Home/Details/17020" },
    { name: "Alpha Epsilon Phi", description: "A sorority promoting sisterhood, scholarship, and leadership.", link: "https://studentorg.ucsd.edu/Home/Details/17021" },
    { name: "Alpha Epsilon Pi", description: "A Jewish fraternity offering leadership opportunities and fostering a sense of community.", link: "https://studentorg.ucsd.edu/Home/Details/17022" },
    { name: "Alpha Phi", description: "A sorority encouraging sisterhood, scholarship, and leadership.", link: "https://studentorg.ucsd.edu/Home/Details/17023" },
    { name: "Alpha Phi Omega", description: "A co-ed fraternity focusing on leadership, friendship, and service.", link: "https://studentorg.ucsd.edu/Home/Details/17024" },
    { name: "Alpine Club at UC San Diego", description: "A club for outdoor enthusiasts focused on climbing and mountaineering.", link: "https://studentorg.ucsd.edu/Home/Details/17025" },
    { name: "Alzheimer's Foundation of America on Campus", description: "Raises awareness about Alzheimer’s disease through education and events.", link: "https://studentorg.ucsd.edu/Home/Details/17026" },
    { name: "Amateur Radio Club at UC San Diego (KK6UC)", description: "A club for amateur radio enthusiasts to learn and operate ham radio systems.", link: "https://studentorg.ucsd.edu/Home/Details/17027" },
    { name: "American Advertising Federation at UC San Diego (AdWave)", description: "Supports students interested in careers in advertising and marketing.", link: "https://studentorg.ucsd.edu/Home/Details/17028" },
    { name: "American Chemical Society Student Affiliates (ACSSA)", description: "Supports students pursuing careers in chemistry and chemical engineering.", link: "https://studentorg.ucsd.edu/Home/Details/17029" },
    { name: "American Institute of Aeronautics and Astronautics", description: "Promotes interest and development in aerospace engineering.", link: "https://studentorg.ucsd.edu/Home/Details/17030" }
];
  
export const recruitmentData = [
    { club_id: 1, title: 'Dancer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 2, title: 'Artist', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 3, title: 'Event Planner', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 4, title: 'Coordinator', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 5, title: 'Mentor', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 6, title: 'Member', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 7, title: 'Facilitator', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 8, title: 'Advocate', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 9, title: 'Volunteer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 10, title: 'Consultant', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 11, title: 'Performer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 12, title: 'Organizer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 13, title: 'Member', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 14, title: 'Developer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 15, title: 'Volunteer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 16, title: 'Player', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 17, title: 'Usher', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 18, title: 'Leader', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 19, title: 'Sister', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 20, title: 'Volunteer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 21, title: 'Event Lead', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 22, title: 'Brother', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 23, title: 'Sister', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 24, title: 'Volunteer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 25, title: 'Hiker', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 26, title: 'Advocate', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 27, title: 'Operator', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 28, title: 'Creative', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 29, title: 'Chemist', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' },
    { club_id: 30, title: 'Engineer', deadline: '2024-12-30 23:59:59', application_link: 'https://example.com/apply' }
];
  
export const eventData = [
    { club_id: 1, title: 'Intro to Hip Hop Dance', date: '2024-12-05 18:00:00', room: 'Dance Studio A', incentives: ['Food', 'Merch'] },
    { club_id: 1, title: 'End of Year Dance Showcase', date: '2024-12-15 19:00:00', room: 'UCSD Main Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 2, title: 'Creative Study Session', date: '2024-12-06 15:00:00', room: '528 Lounge', incentives: ['Food', 'Merch'] },
    { club_id: 2, title: 'Collaborative Art Project', date: '2024-12-12 14:00:00', room: '528 Lounge', incentives: ['Food', 'Merch'] },
    { club_id: 3, title: 'Campus Friendship Mixer', date: '2024-12-07 17:00:00', room: 'Student Center', incentives: ['Food', 'Merch'] },
    { club_id: 3, title: 'Speed Friending', date: '2024-12-14 16:00:00', room: 'Student Center', incentives: ['Food', 'Merch'] },
    { club_id: 4, title: 'Bible Study and Fellowship', date: '2024-12-08 19:00:00', room: 'Chapel Room', incentives: ['Food', 'Merch'] },
    { club_id: 4, title: 'Christmas Potluck Dinner', date: '2024-12-22 18:00:00', room: 'Community Hall', incentives: ['Food', 'Merch'] },
    { club_id: 5, title: 'Study Skills Workshop', date: '2024-12-10 14:00:00', room: 'Library Study Room', incentives: ['Food', 'Merch'] },
    { club_id: 5, title: 'Peer Mentoring Session', date: '2024-12-13 16:00:00', room: 'Student Lounge', incentives: ['Food', 'Merch'] },
    { club_id: 6, title: 'Career Networking Night', date: '2024-12-09 18:30:00', room: 'Career Center', incentives: ['Food', 'Merch'] },
    { club_id: 6, title: 'Managed Care 101 Workshop', date: '2024-12-11 13:00:00', room: 'Pharmacy Building Room 101', incentives: ['Food', 'Merch'] },
    { club_id: 7, title: 'Motivation and Empowerment Workshop', date: '2024-12-05 17:00:00', room: 'Room 203', incentives: ['Food', 'Merch'] },
    { club_id: 7, title: 'Vision Board Creation Event', date: '2024-12-12 18:30:00', room: 'Room 205', incentives: ['Food', 'Merch'] },
    { club_id: 8, title: 'Mental Health Awareness Seminar', date: '2024-12-06 12:00:00', room: 'Health Center Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 8, title: 'Stress Relief Yoga Session', date: '2024-12-13 14:00:00', room: 'Yoga Studio', incentives: ['Food', 'Merch'] },
    { club_id: 9, title: 'Weekly Fellowship Gathering', date: '2024-12-07 18:30:00', room: 'Room 301', incentives: ['Food', 'Merch'] },
    { club_id: 9, title: 'Christmas Caroling Event', date: '2024-12-20 17:00:00', room: 'Student Housing', incentives: ['Food', 'Merch'] },
    { club_id: 10, title: 'Consulting Career Panel', date: '2024-12-10 17:00:00', room: 'Business School Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 10, title: 'Resume Review Session', date: '2024-12-14 15:00:00', room: 'Career Services Center', incentives: ['Food', 'Merch'] },
    { club_id: 11, title: 'Ballet Technique Workshop', date: '2024-12-05 18:00:00', room: 'Dance Studio B', incentives: ['Food', 'Merch'] },
    { club_id: 11, title: 'Holiday Dance Performance', date: '2024-12-18 20:00:00', room: 'Main Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 12, title: 'Afghan Culture Night', date: '2024-12-07 19:00:00', room: 'Student Center', incentives: ['Food', 'Merch'] },
    { club_id: 12, title: 'Afghan Heritage Exhibit', date: '2024-12-14 13:00:00', room: 'Gallery Room', incentives: ['Food', 'Merch'] },
    { club_id: 13, title: 'Islamic Student Community Meet-up', date: '2024-12-09 17:30:00', room: 'Room 106', incentives: ['Food', 'Merch'] },
    { club_id: 13, title: 'Interfaith Dialogue Event', date: '2024-12-16 14:00:00', room: 'Student Lounge', incentives: ['Food', 'Merch'] },
    { club_id: 14, title: 'Intro to AI Workshop', date: '2024-12-08 15:00:00', room: 'Computer Science Lab', incentives: ['Food', 'Merch'] },
    { club_id: 14, title: 'AI and Machine Learning Hackathon', date: '2024-12-13 16:00:00', room: 'Tech Hub', incentives: ['Food', 'Merch'] },
    { club_id: 15, title: 'World AIDS Day Awareness Event', date: '2024-12-01 14:00:00', room: 'Student Center', incentives: ['Food', 'Merch'] },
    { club_id: 15, title: 'HIV Awareness Fundraiser', date: '2024-12-14 18:30:00', room: 'Main Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 16, title: 'Airsoft Training and Games', date: '2024-12-05 14:00:00', room: 'Outdoor Sports Field', incentives: ['Food', 'Merch'] },
    { club_id: 16, title: 'Airsoft Tournament', date: '2024-12-12 10:00:00', room: 'Airsoft Field', incentives: ['Food', 'Merch'] },
    { club_id: 17, title: 'Weekly Worship Service', date: '2024-12-06 18:30:00', room: 'Chapel Room', incentives: ['Food', 'Merch'] },
    { club_id: 17, title: 'Christmas Eve Service', date: '2024-12-24 21:00:00', room: 'Chapel Room', incentives: ['Food', 'Merch'] },
    { club_id: 18, title: 'Leadership Development Workshop', date: '2024-12-07 14:00:00', room: 'Room 405', incentives: ['Food', 'Merch'] },
    { club_id: 18, title: 'Community Service Day', date: '2024-12-14 09:00:00', room: 'Community Center', incentives: ['Food', 'Merch'] },
    { club_id: 19, title: 'Philanthropy Fundraiser', date: '2024-12-10 17:00:00', room: 'Fraternity House', incentives: ['Food', 'Merch'] },
    { club_id: 19, title: 'Sisterhood Social', date: '2024-12-13 18:30:00', room: 'Fraternity House', incentives: ['Food', 'Merch'] },
    { club_id: 20, title: 'Pre-Health Networking Night', date: '2024-12-06 19:00:00', room: 'Health Sciences Building', incentives: ['Food', 'Merch'] },
    { club_id: 20, title: 'Healthcare Career Panel', date: '2024-12-12 17:00:00', room: 'Main Lecture Hall', incentives: ['Food', 'Merch'] },
    { club_id: 21, title: 'Sisterhood Building Event', date: '2024-12-05 16:00:00', room: 'Chapter House', incentives: ['Food', 'Merch'] },
    { club_id: 21, title: 'Charity Walk for Breast Cancer', date: '2024-12-07 10:00:00', room: 'UCSD Campus', incentives: ['Shirts'] },
    { club_id: 22, title: 'Jewish Networking Event', date: '2024-12-09 18:00:00', room: 'Room 208', incentives: ['Food', 'Merch'] },
    { club_id: 22, title: 'Chanukah Celebration', date: '2024-12-12 19:30:00', room: 'Student Center', incentives: ['Food', 'Merch'] },
    { club_id: 23, title: 'Sisterhood Social', date: '2024-12-10 18:00:00', room: 'Fraternity House', incentives: ['Food', 'Merch'] },
    { club_id: 23, title: 'Philanthropy Fundraiser', date: '2024-12-14 16:00:00', room: 'Fraternity House', incentives: ['Food', 'Merch'] },
    { club_id: 24, title: 'Community Service Project', date: '2024-12-07 09:00:00', room: 'Park Area', incentives: ['Food', 'Merch'] },
    { club_id: 24, title: 'Leadership Training Workshop', date: '2024-12-13 17:00:00', room: 'Room 301', incentives: ['Food', 'Merch'] },
    { club_id: 25, title: 'Mountain Climbing Trip', date: '2024-12-12 06:00:00', room: 'Meet at Student Center', incentives: ['Shirts'] },
    { club_id: 25, title: 'Winter Hike and Picnic', date: '2024-12-15 10:00:00', room: 'Mount Laguna', incentives: ['Shirts'] },
    { club_id: 26, title: 'Awareness Campaign: Alzheimer’s Disease', date: '2024-12-03 14:00:00', room: 'Student Center', incentives: ['Stickers'] },
    { club_id: 26, title: 'Memory Walk Fundraiser', date: '2024-12-08 09:00:00', room: 'UCSD Campus', incentives: ['Shirts'] },
    { club_id: 27, title: 'Beginner’s Ham Radio Workshop', date: '2024-12-06 18:00:00', room: 'Room 405', incentives: ['Stickers'] },
    { club_id: 27, title: 'Annual Ham Radio Operation', date: '2024-12-14 10:00:00', room: 'Radio Station', incentives: ['Stickers'] },
    { club_id: 28, title: 'Advertising Career Night', date: '2024-12-09 18:30:00', room: 'Business School Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 28, title: 'Creative Ad Campaign Workshop', date: '2024-12-11 16:00:00', room: 'Creative Studio', incentives: ['Food', 'Merch'] },
    { club_id: 29, title: 'Chemistry Career Panel', date: '2024-12-06 17:00:00', room: 'Science Building Auditorium', incentives: ['Food', 'Merch'] },
    { club_id: 29, title: 'Chemistry Lab Tour and Talk', date: '2024-12-13 15:00:00', room: 'Chemistry Lab', incentives: ['Food', 'Merch'] },
    { club_id: 30, title: 'Mock Interview Practice Session', date: '2024-12-07 16:00:00', room: 'Law School Courtroom', incentives: ['Food', 'Merch'] },
    { club_id: 30, title: 'Getting into a Research Lab', date: '2024-12-14 13:00:00', room: 'Room 207', incentives: ['Food', 'Merch'] }
  ];
  